# .github/workflows/deploy.yml
name: Deploy a servidor remoto

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar clave SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Desplegar vía SSH
      run: |
        ssh -o StrictHostKeyChecking=no alumno@137.184.127.11 'cd lemp-sites/nahuel_silva/dev-ops-js && git pull && npm install && npm run build'
